---

- name: Installation de Gitlab CE
  become: true
  shell: 'apt-get install sudo curl git && curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash && apt-get install gitlab-ce'
#  when: ansible_host == "192.168.203.133"
  when: ansible_host == "172.16.230.18"
  run_once: true

- name: Installation du runner Gitlab CI
  become: true
  shell: 'curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.deb.sh | sudo bash && apt install gitlab-ci-multi-runner'
#  when: ansible_host == "192.168.203.133"
  when: ansible_host == "172.16.230.18"
  run_once: true

- name: Init gitlab-ci-multi-runner register
  become: true
  shell: 'gitlab-ci-multi-runner register'
  when: ansible_host == "172.16.230.18"
  run_once: true


  
