---
- name: Set concurrent option
  become: true
  lineinfile:
    dest: /etc/gitlab-runner/config.toml
    regexp: ^concurrent =
    line: concurrent = {{ gitlab_runner_concurrent }}
    state: present
